### ISSUE TITLE
After configuring BGP peer-group, output contains superfluous entries

### ISSUE THREAD

**Issue by xivamar** [MERAprojects/ops-build#10]
## Problem Description:
After configuring BGP peer-group, output contains superfluous entries. 

## OpenSwitch version:
OpenSwitch 0.4.0 (Build: appliance-ops-0.4.0-devel/master-20161123113643-dev)

## Test Topology:
This issue may be reproduced on single DUT

## Steps to reproduce the problem (see attached file):
1. Configure DUT as in attached file.
2. Configure BGP peer-group on DUT:
  
 ```
switch# conf ter
switch(config)# router bgp 77
switch(config-router)# neighbor 172.16.10.1 remote-as 65502
switch(config-router)# neighbor 172.17.10.1 remote-as 65504
switch(config-router)# 
switch(config-router)# neighbor AS_77 peer-group 
switch(config-router)# neighbor AS_77 remote-as 77
switch(config-router)# neighbor AS_77 update-source loopback1
switch(config-router)# neighbor 1.1.1.1 peer-group AS_77
switch(config-router)# neighbor 2.2.2.2 peer-group AS_77
switch(config-router)# neighbor 3.3.3.3 peer-group AS_77
switch(config-router)# no bgp fast-external-failover
switch(config-router)# end
   ```

3. Check configuration on DUT. - `NOK: output contains superfluous entries`. 

 ```
 switch# show running-config        
Current configuration:
!
!Version OpenSwitch 0.4.0 (Build: appliance-ops-0.4.0-devel/master-20161123113643-dev)
!Schema version 0.1.8
timezone set utc
!
!
!
aaa authentication login default local
aaa authorization commands default none
!
!
!
!
router bgp 77
     neighbor AS_77 peer-group
     neighbor 1.1.1.1 remote-as 77            <-- лишнее, не должно быть
     neighbor 1.1.1.1 peer-group AS_77
     neighbor 172.16.10.1 remote-as 65502
     neighbor 172.17.10.1 remote-as 65504
     neighbor 2.2.2.2 remote-as 77            <-- лишнее, не должно быть
     neighbor 2.2.2.2 peer-group AS_77
     neighbor 3.3.3.3 remote-as 77            <-- лишнее, не должно быть
     neighbor 3.3.3.3 peer-group AS_77
     neighbor AS_77 remote-as 77
     neighbor AS_77 update-source loopback1
!
(дальше пропущено)
   ```

[config.txt](https://github.com/MERAprojects/ops-build/files/613173/config.txt)

**Comment by AKochin** [comment]
Hello,

Could you please be so kind to clarify what is the expected behavior here?

When I've replicated the problem on my env I'vefound more superfluous entries:

neighbor 2.2.2.2 remote-as 77  
neighbor 2.2.2.2 weight 0

Should I remove this also? 

As I understand when neighr is in peer-group it should inherit all attributes from peer-group and has no individual settings. Am I right?

Best regards,
Andrey.

**Comment by AKochin** [comment]
https://github.com/MERAprojects/ops-cli/pull/24

**Comment by AKochin** [comment]
Hello, do we need any verification here to close this task?

**Comment by xivamar** [comment]
Issue is fixed on build:

     switch# show version 
     OpenSwitch 0.4.0 (Build: appliance-ops-0.4.0-meraswitch/devel/master-20170329113554-dev)
     switch#
