### ISSUE TITLE
Segmentation fault was returned after trying to check STP status

### ISSUE THREAD

**Issue by xivamar** [MERAprojects/ops-build#30]
Problem Description:
---------------------
If configuration contains more than 2 VLANs, the `show spanning-tree` command returns segmentation fault.

OpenSwitch version:
---------------------
OpenSwitch 0.4.0 (Build: appliance-ops-0.4.0-meraswitch/devel/master-20170126080249-dev)

Test Topology:
---------------------
![topology_vlan_stp_small](https://cloud.githubusercontent.com/assets/19854384/22883575/db2aa0f0-f201-11e6-9d26-3af28f1ae0b5.png)

Steps to reproduce the problem (see attached files):
----------------------------------------------------
1. Configure DUTs as in attached file.
2. Try to check STP status on OpenSwitch-2. - `NOK: segmentation fault`.

        switch# show spanning-tree 
        MST0
        Spanning tree status: Enabled
        Root ID    Priority   : 16384               
             MAC-Address: 70:72:cf:2f:6b:a9   
             This bridge is the root
             Hello time(in seconds):2  Max Age(in seconds):20  Forward Delay(in seconds):15

        Bridge ID  Priority  : 16384               
             MAC-Address: 70:72:cf:2f:6b:a9   
             Hello time(in seconds):2  Max Age(in seconds):20  Forward Delay(in seconds):15

        Port         Role           State      Cost    Priority   Type
        ------------ -------------- ---------- ------- ---------- ----------
        Segmentation fault
        root@switch:~# 
        root@switch:~# 
        root@switch:~# vtysh 
        switch# 
        switch# 
        switch# show spanning-tree detail 
        MST0
          Spanning tree status: Enabled
          Root ID    Priority   : 16384               
             MAC-Address: 70:72:cf:2f:6b:a9   
             This bridge is the root
             Hello time(in seconds):2  Max Age(in seconds):20  Forward Delay(in seconds):15

          Bridge ID  Priority  : 16384               
             MAC-Address: 70:72:cf:2f:6b:a9   
             Hello time(in seconds):2  Max Age(in seconds):20  Forward Delay(in seconds):15

        Port         Role           State      Cost    Priority   Type
        ------------ -------------- ---------- ------- ---------- ----------
        Segmentation fault
        root@switch:~# 

[vlan_stp.txt](https://github.com/MERAprojects/ops-build/files/771066/vlan_stp.txt)

**Comment by AKochin** [comment]
Issue is fixed. Needs to be verified and closed.

**Comment by xivamar** [comment]
Issue has been fixed. It was verified on the build:

    switch# show version 
    OpenSwitch 0.4.0 (Build: appliance-ops-0.4.0-meraswitch/devel/master-20170329113554-dev)
    switch#
