### ISSUE TITLE
Ping is absent when interfaces are configured as L2 or L3 lag

### ISSUE THREAD

**Issue by xivamar** [MERAprojects/ops-build#4]
## Problem Description:

Ping is absent when interfaces are configured as L2 or L3 lag
## OpenSwitch version:

OpenSwitch 0.4.0 (Build: appliance-ops-0.4.0-master-20161007085740-dev)
OpenSwitch 1.0.0 (Build: appliance-ops-1.0.0-rel/dill-20161003142541-dev)
## Test Topology:

![screenshot](https://cloud.githubusercontent.com/assets/19854384/19182917/840fe70a-8c7e-11e6-8ece-9318309a73a7.png)
## Steps to reproduce the problem:
1. Configure DUTs as in attached file.
2. Check adjacency via `show lacp interfaces` on DUT2:
   
   ```
   switch# show lacp interfaces
   
   State abbreviations :
   A - Active        P - Passive      F - Aggregable I - Individual
   S - Short-timeout L - Long-timeout N - InSync     O - OutofSync
   C - Collecting    D - Distributing 
   X - State m/c expired              E - Default neighbor state
   
   Actor details of all interfaces:
   ------------------------------------------------------------------------------
   Intf Aggregate Port    Port     Key  State   System-id         System   Aggr    
   name      id      Priority                                Priority Key     
   ------------------------------------------------------------------------------
   eth2 lag12     9       1        12   ALFNCD  70:72:cf:0e:80:1a 65534    12      
   eth1 lag12     5       1        12   ALFNCD  70:72:cf:0e:80:1a 65534    12      
   
   
   Partner details of all interfaces:
   ------------------------------------------------------------------------------
   Intf Aggregate Partner Port     Key  State   System-id         System   Aggr    
        name      Port-id Priority                                Priority Key     
   ------------------------------------------------------------------------------
   eth2 lag12     9       1        12   ALFNCD  70:72:cf:ea:da:40 65534    12      
   eth1 lag12     5       1        12   ALFNCD  70:72:cf:ea:da:40 65534    12      
   switch# 
   ```
3. Try to sent ping. - NOK: `Ping is absent`

[LAG_config.txt](https://github.com/MERAprojects/ops-build/files/516010/LAG_config.txt)

**Comment by kontorschikov** [comment]
Hi.

OpenSwitch needs Linux bonding driver loaded in order to create LAGs (http://www.openswitch.net/documents/user/link_aggregation_design)

Please try loading the driver on the host OS by using command "**modprobe bonding**" before starting the test case.

**Comment by xivamar** [comment]
Hi,

Should user load bonding driver himself? Is it correct behaver?

    root@switch:~# modprobe bonding
    root@switch:~# 
    root@switch:~# lsmod | grep bonding
    root@switch:~# 
    root@switch:~# modinfo bonding
    modinfo: ERROR: Module alias bonding not found.
    root@switch:~# 

The test result is as in issue.

**Comment by kontorschikov** [comment]
Hi,

The command should be used on the **host OS** (i.e. Ubuntu) since the docker container uses host OS kernel.

**Comment by xivamar** [comment]
Hi,

        marina@ubuntu:~$ sudo modprobe bonding
        [sudo] password for marina: 
        marina@ubuntu:~$ 
        marina@ubuntu:~$  lsmod | grep bonding
        bonding               139264  0 
        marina@ubuntu:~$ 

Now ping is present in both cases (L2 or L3 lag). And ifconfig output contains lag entries:

        root@switch:~#ip netns exec swns ifconfig
        .......(missed).......
        lag12     Link encap:Ethernet  HWaddr 70:72:CF:AF:66:07
                  inet addr:10.0.0.1  Bcast:0.0.0.0  Mask:255.255.255.0
                  UP BROADCAST RUNNING MASTER MULTICAST  MTU:1500  Metric:1
                  RX packets:23 errors:0 dropped:0 overruns:0 frame:0
                  TX packets:25 errors:0 dropped:0 overruns:0 carrier:0
                  collisions:0 txqueuelen:1000
                  RX bytes:2382  TX bytes:2568

        lo        Link encap:Local Loopback
                  inet addr:127.0.0.1  Mask:255.0.0.0
                  UP LOOPBACK RUNNING  MTU:65536  Metric:1
                  RX packets:0 errors:0 dropped:0 overruns:0 frame:0
                  TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
                  collisions:0 txqueuelen:1
                  RX bytes:0  TX bytes:0

        root@switch:~#

**Comment by xivamar** [comment]
Issue has been fixed including some additional matter
