### ISSUE TITLE
IPv6 static routes aren't configured

### ISSUE THREAD

**Issue by xivamar** [MERAprojects/ops-build#8]
## Problem Description:
On DUT2 we configure static routes and distribute its in OSPF.  But routing table on other DUTs doesn't contain static routes.

## OpenSwitch version:
OpenSwitch 0.4.0 (Build: appliance-ops-0.4.0-devel/master-20161107122528-dev)

## Test Topology:
![screenshot](https://cloud.githubusercontent.com/assets/19854384/20175295/156e8348-a753-11e6-8a3a-f6c2596f03f6.png)

## Steps to reproduce the problem:
1. Configure DUTs .
2. Configure static routes on DUT1. - NOK: `Error message`:

       switch# configure terminal 
       switch(config)# ipv6 route 2002::6500:8/126 2002::6500:1
       vtysh: symbol lookup error: /usr/lib/cli/plugins/libl3routes_cli.so: undefined symbol: ip_addr_is_equal_af
       root@switch:~# 

In full notation:

       switch# conf ter
       switch(config)# ipv6 route 2002:0:0:0:0:0:6600:8/126 2002:0:0:0:0:0:6500:1
       
       Invalid prefix. Valid prefix: 2002::6600:8/126
       % Command failed.
       switch(config)# 
       switch(config)#  ipv6 route 2002::6600:8/126 2002:0:0:0:0:0:6500:1
       vtysh: symbol lookup error: /usr/lib/cli/plugins/libl3routes_cli.so: undefined symbol: ip_addr_is_equal_af
       root@switch:~#

**Comment by ekgrish** [comment]
Pull request: https://github.com/MERAprojects/ops-cli/pull/26

related to: 
https://github.com/MERAprojects/ops-quagga/issues/7
https://github.com/MERAprojects/ops-quagga/pull/31

**Comment by ekgrish** [comment]
Pull request MERAprojects/ops-cli#26 has been merged
